### ISSUE TITLE
"Extension of a generic Objective-C class cannot access the class's generic parameter at runtime"

### ISSUE THREAD

**Issue by haemi** [wibosco/CoreDataServices#22]
I do get the above compile error with version `~> 3.2.2` installed via Cocoapods; is this a known issue or am I missing something?

**Comment by wibosco** [comment]
@haemi thanks for highlighting this issue. Have you recently upgraded your project to using `swift 4`? 

I believe this bug was the result of changes that `swift 4` introduced how it handles ObjC->Swift interfaces. 

I've released a new version of this pod `4.0.0`, where I've resolved this issue. Let me know if after updating to `4.0.0` you still have this issue
